### ISSUE TITLE
Some questions about train script

### ISSUE THREAD

**Issue by vlad3996** [lancopku/simNet#1]
Hi! Thanks for sharing code for your paper. I have some questions about train script:

- **caption_path**='./data/annotations/karpathy_split_train.json' - this is path to COCO captions json (annotations/captions_train2014.json [from here](http://images.cocodataset.org/annotations/annotations_trainval2014.zip))? Did you modify json? 
- **topic_path**='./data/topics/image_topic.json' - this is path to COCO instances json (annotations/instances_train2014.json [from here](http://images.cocodataset.org/annotations/annotations_trainval2014.zip) ) ? 

- **vocab_path**='vocab.pkl' - as I understand, that's some custom mapper for vocab used [here](https://github.com/s-gupta/visual-concepts/tree/master/vocabs) with custom "words" `<start>` and `<end>`. This mapper map words from caption to one-hot or other embedding vectors. Can you provide your 'vocab.pkl' to reproduce results ?

**Comment by ictLiuFenglin** [comment]
Hi！
Thank you for the feedback.
**caption_path**: We have uploaded a file called "KarpathySplit.py" which can be used to generate "karpathy_split_train.json"

**topic_path**: You can get the topic by referring to https://github.com/eriche2016/image_caption_with_semantic_attenion.

**vocab_path**: You can get the 'vocab.pkl' by running "build_vocab.py"

Wishing success！
